# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1734, 787)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 841, 751))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.vr1Split1RadioEdge = QtGui.QRadioButton(self.tabWidgetPage1)
        self.vr1Split1RadioEdge.setGeometry(QtCore.QRect(110, 50, 61, 19))
        self.vr1Split1RadioEdge.setChecked(False)
        self.vr1Split1RadioEdge.setObjectName(_fromUtf8("vr1Split1RadioEdge"))
        self.vr1Split1Group = QtGui.QButtonGroup(MainWindow)
        self.vr1Split1Group.setObjectName(_fromUtf8("vr1Split1Group"))
        self.vr1Split1Group.addButton(self.vr1Split1RadioEdge)
        self.vr1Split1RadioRegional = QtGui.QRadioButton(self.tabWidgetPage1)
        self.vr1Split1RadioRegional.setGeometry(QtCore.QRect(180, 50, 98, 19))
        self.vr1Split1RadioRegional.setChecked(True)
        self.vr1Split1RadioRegional.setObjectName(_fromUtf8("vr1Split1RadioRegional"))
        self.vr1Split1Group.addButton(self.vr1Split1RadioRegional)
        self.label = QtGui.QLabel(self.tabWidgetPage1)
        self.label.setGeometry(QtCore.QRect(40, 50, 58, 14))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 58, 14))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.vr1Split2RadioEdge = QtGui.QRadioButton(self.tabWidgetPage1)
        self.vr1Split2RadioEdge.setGeometry(QtCore.QRect(110, 80, 61, 19))
        self.vr1Split2RadioEdge.setChecked(False)
        self.vr1Split2RadioEdge.setObjectName(_fromUtf8("vr1Split2RadioEdge"))
        self.vr1Split2Group = QtGui.QButtonGroup(MainWindow)
        self.vr1Split2Group.setObjectName(_fromUtf8("vr1Split2Group"))
        self.vr1Split2Group.addButton(self.vr1Split2RadioEdge)
        self.vr1Split2RadioRegional = QtGui.QRadioButton(self.tabWidgetPage1)
        self.vr1Split2RadioRegional.setGeometry(QtCore.QRect(180, 80, 98, 19))
        self.vr1Split2RadioRegional.setChecked(True)
        self.vr1Split2RadioRegional.setObjectName(_fromUtf8("vr1Split2RadioRegional"))
        self.vr1Split2Group.addButton(self.vr1Split2RadioRegional)
        self.label_3 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 58, 14))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.vr1Split3RadioEdge = QtGui.QRadioButton(self.tabWidgetPage1)
        self.vr1Split3RadioEdge.setGeometry(QtCore.QRect(110, 110, 61, 19))
        self.vr1Split3RadioEdge.setChecked(False)
        self.vr1Split3RadioEdge.setObjectName(_fromUtf8("vr1Split3RadioEdge"))
        self.vr1Split3Group = QtGui.QButtonGroup(MainWindow)
        self.vr1Split3Group.setObjectName(_fromUtf8("vr1Split3Group"))
        self.vr1Split3Group.addButton(self.vr1Split3RadioEdge)
        self.vr1Split3RadioRegional = QtGui.QRadioButton(self.tabWidgetPage1)
        self.vr1Split3RadioRegional.setGeometry(QtCore.QRect(180, 110, 98, 19))
        self.vr1Split3RadioRegional.setChecked(True)
        self.vr1Split3RadioRegional.setObjectName(_fromUtf8("vr1Split3RadioRegional"))
        self.vr1Split3Group.addButton(self.vr1Split3RadioRegional)
        self.groupBox = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.vr1SplitView = QtGui.QLabel(self.groupBox)
        self.vr1SplitView.setGeometry(QtCore.QRect(280, 0, 231, 151))
        self.vr1SplitView.setAutoFillBackground(False)
        self.vr1SplitView.setText(_fromUtf8(""))
        self.vr1SplitView.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/vr1_split_d.png")))
        self.vr1SplitView.setScaledContents(True)
        self.vr1SplitView.setWordWrap(False)
        self.vr1SplitView.setObjectName(_fromUtf8("vr1SplitView"))
        self.vr1ToogleAll = QtGui.QPushButton(self.groupBox)
        self.vr1ToogleAll.setGeometry(QtCore.QRect(200, 130, 79, 24))
        self.vr1ToogleAll.setDefault(False)
        self.vr1ToogleAll.setFlat(False)
        self.vr1ToogleAll.setObjectName(_fromUtf8("vr1ToogleAll"))
        self.vr1AllEdge = QtGui.QPushButton(self.groupBox)
        self.vr1AllEdge.setGeometry(QtCore.QRect(10, 130, 79, 24))
        self.vr1AllEdge.setDefault(False)
        self.vr1AllEdge.setFlat(False)
        self.vr1AllEdge.setObjectName(_fromUtf8("vr1AllEdge"))
        self.vr1AllEdge_2 = QtGui.QPushButton(self.groupBox)
        self.vr1AllEdge_2.setGeometry(QtCore.QRect(90, 130, 79, 24))
        self.vr1AllEdge_2.setDefault(False)
        self.vr1AllEdge_2.setFlat(False)
        self.vr1AllEdge_2.setObjectName(_fromUtf8("vr1AllEdge_2"))
        self.vr1DownlinkPlot = PlotWidget(self.tabWidgetPage1)
        self.vr1DownlinkPlot.setGeometry(QtCore.QRect(10, 180, 811, 261))
        self.vr1DownlinkPlot.setObjectName(_fromUtf8("vr1DownlinkPlot"))
        self.vr1UplinkPlot = PlotWidget(self.tabWidgetPage1)
        self.vr1UplinkPlot.setGeometry(QtCore.QRect(10, 450, 811, 261))
        self.vr1UplinkPlot.setObjectName(_fromUtf8("vr1UplinkPlot"))
        self.vr1Split1DownlinkLCD = QtGui.QLCDNumber(self.tabWidgetPage1)
        self.vr1Split1DownlinkLCD.setGeometry(QtCore.QRect(600, 200, 64, 23))
        self.vr1Split1DownlinkLCD.setAutoFillBackground(True)
        self.vr1Split1DownlinkLCD.setSmallDecimalPoint(True)
        self.vr1Split1DownlinkLCD.setNumDigits(4)
        self.vr1Split1DownlinkLCD.setDigitCount(4)
        self.vr1Split1DownlinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr1Split1DownlinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr1Split1DownlinkLCD.setObjectName(_fromUtf8("vr1Split1DownlinkLCD"))
        self.vr1Split2DownlinkLCD = QtGui.QLCDNumber(self.tabWidgetPage1)
        self.vr1Split2DownlinkLCD.setGeometry(QtCore.QRect(670, 200, 64, 23))
        self.vr1Split2DownlinkLCD.setAutoFillBackground(True)
        self.vr1Split2DownlinkLCD.setSmallDecimalPoint(False)
        self.vr1Split2DownlinkLCD.setDigitCount(4)
        self.vr1Split2DownlinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr1Split2DownlinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr1Split2DownlinkLCD.setObjectName(_fromUtf8("vr1Split2DownlinkLCD"))
        self.vr1Split3DownlinkLCD = QtGui.QLCDNumber(self.tabWidgetPage1)
        self.vr1Split3DownlinkLCD.setGeometry(QtCore.QRect(750, 200, 64, 23))
        self.vr1Split3DownlinkLCD.setAutoFillBackground(True)
        self.vr1Split3DownlinkLCD.setSmallDecimalPoint(False)
        self.vr1Split3DownlinkLCD.setDigitCount(4)
        self.vr1Split3DownlinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr1Split3DownlinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr1Split3DownlinkLCD.setObjectName(_fromUtf8("vr1Split3DownlinkLCD"))
        self.vr1Split1UplinkLCD = QtGui.QLCDNumber(self.tabWidgetPage1)
        self.vr1Split1UplinkLCD.setGeometry(QtCore.QRect(750, 460, 64, 23))
        self.vr1Split1UplinkLCD.setAutoFillBackground(True)
        self.vr1Split1UplinkLCD.setSmallDecimalPoint(True)
        self.vr1Split1UplinkLCD.setNumDigits(4)
        self.vr1Split1UplinkLCD.setDigitCount(4)
        self.vr1Split1UplinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr1Split1UplinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr1Split1UplinkLCD.setObjectName(_fromUtf8("vr1Split1UplinkLCD"))
        self.label_5 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_5.setGeometry(QtCore.QRect(540, 200, 58, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_12 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_12.setGeometry(QtCore.QRect(690, 460, 58, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.vr1Split1DownlinkAvgLCD = QtGui.QLCDNumber(self.tabWidgetPage1)
        self.vr1Split1DownlinkAvgLCD.setGeometry(QtCore.QRect(600, 230, 64, 23))
        self.vr1Split1DownlinkAvgLCD.setAutoFillBackground(True)
        self.vr1Split1DownlinkAvgLCD.setSmallDecimalPoint(True)
        self.vr1Split1DownlinkAvgLCD.setNumDigits(4)
        self.vr1Split1DownlinkAvgLCD.setDigitCount(4)
        self.vr1Split1DownlinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr1Split1DownlinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr1Split1DownlinkAvgLCD.setObjectName(_fromUtf8("vr1Split1DownlinkAvgLCD"))
        self.vr1Split2DownlinkAvgLCD = QtGui.QLCDNumber(self.tabWidgetPage1)
        self.vr1Split2DownlinkAvgLCD.setGeometry(QtCore.QRect(670, 230, 64, 23))
        self.vr1Split2DownlinkAvgLCD.setAutoFillBackground(True)
        self.vr1Split2DownlinkAvgLCD.setSmallDecimalPoint(False)
        self.vr1Split2DownlinkAvgLCD.setDigitCount(4)
        self.vr1Split2DownlinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr1Split2DownlinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr1Split2DownlinkAvgLCD.setObjectName(_fromUtf8("vr1Split2DownlinkAvgLCD"))
        self.vr1Split3DownlinkAvgLCD = QtGui.QLCDNumber(self.tabWidgetPage1)
        self.vr1Split3DownlinkAvgLCD.setGeometry(QtCore.QRect(750, 230, 64, 23))
        self.vr1Split3DownlinkAvgLCD.setAutoFillBackground(True)
        self.vr1Split3DownlinkAvgLCD.setSmallDecimalPoint(False)
        self.vr1Split3DownlinkAvgLCD.setDigitCount(4)
        self.vr1Split3DownlinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr1Split3DownlinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr1Split3DownlinkAvgLCD.setObjectName(_fromUtf8("vr1Split3DownlinkAvgLCD"))
        self.label_21 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_21.setGeometry(QtCore.QRect(560, 230, 31, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.vr1Split1UplinkAvgLCD = QtGui.QLCDNumber(self.tabWidgetPage1)
        self.vr1Split1UplinkAvgLCD.setGeometry(QtCore.QRect(750, 490, 64, 23))
        self.vr1Split1UplinkAvgLCD.setAutoFillBackground(True)
        self.vr1Split1UplinkAvgLCD.setSmallDecimalPoint(True)
        self.vr1Split1UplinkAvgLCD.setNumDigits(4)
        self.vr1Split1UplinkAvgLCD.setDigitCount(4)
        self.vr1Split1UplinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr1Split1UplinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr1Split1UplinkAvgLCD.setObjectName(_fromUtf8("vr1Split1UplinkAvgLCD"))
        self.label_22 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_22.setGeometry(QtCore.QRect(710, 490, 31, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.vr1Amplitude = QtGui.QSlider(self.tabWidgetPage1)
        self.vr1Amplitude.setGeometry(QtCore.QRect(580, 40, 211, 16))
        self.vr1Amplitude.setMaximum(100)
        self.vr1Amplitude.setProperty("value", 50)
        self.vr1Amplitude.setOrientation(QtCore.Qt.Horizontal)
        self.vr1Amplitude.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.vr1Amplitude.setObjectName(_fromUtf8("vr1Amplitude"))
        self.label_31 = QtGui.QLabel(self.tabWidgetPage1)
        self.label_31.setGeometry(QtCore.QRect(650, 10, 81, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.groupBox.raise_()
        self.vr1Split1RadioEdge.raise_()
        self.vr1Split1RadioRegional.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.vr1Split2RadioEdge.raise_()
        self.vr1Split2RadioRegional.raise_()
        self.label_3.raise_()
        self.vr1Split3RadioEdge.raise_()
        self.vr1Split3RadioRegional.raise_()
        self.vr1DownlinkPlot.raise_()
        self.vr1UplinkPlot.raise_()
        self.vr1Split1DownlinkLCD.raise_()
        self.vr1Split2DownlinkLCD.raise_()
        self.vr1Split3DownlinkLCD.raise_()
        self.vr1Split1UplinkLCD.raise_()
        self.label_5.raise_()
        self.label_12.raise_()
        self.vr1Split1DownlinkAvgLCD.raise_()
        self.vr1Split2DownlinkAvgLCD.raise_()
        self.vr1Split3DownlinkAvgLCD.raise_()
        self.label_21.raise_()
        self.vr1Split1UplinkAvgLCD.raise_()
        self.label_22.raise_()
        self.vr1Amplitude.raise_()
        self.label_31.raise_()
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 521, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 50, 58, 14))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_8.setGeometry(QtCore.QRect(180, 50, 81, 19))
        self.radioButton_8.setChecked(False)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.vr2Group = QtGui.QButtonGroup(MainWindow)
        self.vr2Group.setObjectName(_fromUtf8("vr2Group"))
        self.vr2Group.addButton(self.radioButton_8)
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(110, 50, 61, 19))
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.vr2Group.addButton(self.radioButton_7)
        self.vr2SplitView = QtGui.QLabel(self.groupBox_2)
        self.vr2SplitView.setGeometry(QtCore.QRect(280, 0, 231, 151))
        self.vr2SplitView.setText(_fromUtf8(""))
        self.vr2SplitView.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/vr2_split_b.png")))
        self.vr2SplitView.setScaledContents(True)
        self.vr2SplitView.setWordWrap(False)
        self.vr2SplitView.setObjectName(_fromUtf8("vr2SplitView"))
        self.vr2DownlinkPlot = PlotWidget(self.tab)
        self.vr2DownlinkPlot.setGeometry(QtCore.QRect(10, 180, 811, 261))
        self.vr2DownlinkPlot.setObjectName(_fromUtf8("vr2DownlinkPlot"))
        self.vr2UplinkPlot = PlotWidget(self.tab)
        self.vr2UplinkPlot.setGeometry(QtCore.QRect(10, 450, 811, 261))
        self.vr2UplinkPlot.setObjectName(_fromUtf8("vr2UplinkPlot"))
        self.vr2Split1DownlinkLCD = QtGui.QLCDNumber(self.tab)
        self.vr2Split1DownlinkLCD.setGeometry(QtCore.QRect(750, 200, 64, 23))
        self.vr2Split1DownlinkLCD.setAutoFillBackground(True)
        self.vr2Split1DownlinkLCD.setSmallDecimalPoint(True)
        self.vr2Split1DownlinkLCD.setNumDigits(4)
        self.vr2Split1DownlinkLCD.setDigitCount(4)
        self.vr2Split1DownlinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr2Split1DownlinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr2Split1DownlinkLCD.setObjectName(_fromUtf8("vr2Split1DownlinkLCD"))
        self.vr2Split1UplinkLCD = QtGui.QLCDNumber(self.tab)
        self.vr2Split1UplinkLCD.setGeometry(QtCore.QRect(750, 460, 64, 23))
        self.vr2Split1UplinkLCD.setAutoFillBackground(True)
        self.vr2Split1UplinkLCD.setSmallDecimalPoint(True)
        self.vr2Split1UplinkLCD.setNumDigits(4)
        self.vr2Split1UplinkLCD.setDigitCount(4)
        self.vr2Split1UplinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr2Split1UplinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr2Split1UplinkLCD.setObjectName(_fromUtf8("vr2Split1UplinkLCD"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(700, 200, 58, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(690, 460, 58, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.vr2Split1DownlinkAvgLCD = QtGui.QLCDNumber(self.tab)
        self.vr2Split1DownlinkAvgLCD.setGeometry(QtCore.QRect(750, 230, 64, 23))
        self.vr2Split1DownlinkAvgLCD.setAutoFillBackground(True)
        self.vr2Split1DownlinkAvgLCD.setSmallDecimalPoint(True)
        self.vr2Split1DownlinkAvgLCD.setNumDigits(4)
        self.vr2Split1DownlinkAvgLCD.setDigitCount(4)
        self.vr2Split1DownlinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr2Split1DownlinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr2Split1DownlinkAvgLCD.setObjectName(_fromUtf8("vr2Split1DownlinkAvgLCD"))
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(710, 230, 31, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.vr2Split1UplinkAvgLCD = QtGui.QLCDNumber(self.tab)
        self.vr2Split1UplinkAvgLCD.setGeometry(QtCore.QRect(750, 490, 64, 23))
        self.vr2Split1UplinkAvgLCD.setAutoFillBackground(True)
        self.vr2Split1UplinkAvgLCD.setSmallDecimalPoint(True)
        self.vr2Split1UplinkAvgLCD.setNumDigits(4)
        self.vr2Split1UplinkAvgLCD.setDigitCount(4)
        self.vr2Split1UplinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.vr2Split1UplinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vr2Split1UplinkAvgLCD.setObjectName(_fromUtf8("vr2Split1UplinkAvgLCD"))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(710, 490, 31, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(650, 10, 81, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.vr2Amplitude = QtGui.QSlider(self.tab)
        self.vr2Amplitude.setGeometry(QtCore.QRect(580, 40, 211, 16))
        self.vr2Amplitude.setMaximum(100)
        self.vr2Amplitude.setProperty("value", 50)
        self.vr2Amplitude.setOrientation(QtCore.Qt.Horizontal)
        self.vr2Amplitude.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.vr2Amplitude.setObjectName(_fromUtf8("vr2Amplitude"))
        self.vr2ToogleAll = QtGui.QPushButton(self.tab)
        self.vr2ToogleAll.setGeometry(QtCore.QRect(210, 140, 79, 24))
        self.vr2ToogleAll.setObjectName(_fromUtf8("vr2ToogleAll"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.usrpDownlinkPlot = PlotWidget(self.tab_2)
        self.usrpDownlinkPlot.setGeometry(QtCore.QRect(10, 180, 811, 261))
        self.usrpDownlinkPlot.setObjectName(_fromUtf8("usrpDownlinkPlot"))
        self.usrpUplinkPlot = PlotWidget(self.tab_2)
        self.usrpUplinkPlot.setGeometry(QtCore.QRect(10, 450, 811, 261))
        self.usrpUplinkPlot.setObjectName(_fromUtf8("usrpUplinkPlot"))
        self.usrpVr1DownlinkLCD = QtGui.QLCDNumber(self.tab_2)
        self.usrpVr1DownlinkLCD.setGeometry(QtCore.QRect(680, 190, 64, 23))
        self.usrpVr1DownlinkLCD.setAutoFillBackground(True)
        self.usrpVr1DownlinkLCD.setSmallDecimalPoint(True)
        self.usrpVr1DownlinkLCD.setNumDigits(4)
        self.usrpVr1DownlinkLCD.setDigitCount(4)
        self.usrpVr1DownlinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.usrpVr1DownlinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.usrpVr1DownlinkLCD.setObjectName(_fromUtf8("usrpVr1DownlinkLCD"))
        self.usrpVr1UplinkLCD = QtGui.QLCDNumber(self.tab_2)
        self.usrpVr1UplinkLCD.setGeometry(QtCore.QRect(680, 460, 64, 23))
        self.usrpVr1UplinkLCD.setAutoFillBackground(True)
        self.usrpVr1UplinkLCD.setSmallDecimalPoint(True)
        self.usrpVr1UplinkLCD.setNumDigits(4)
        self.usrpVr1UplinkLCD.setDigitCount(4)
        self.usrpVr1UplinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.usrpVr1UplinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.usrpVr1UplinkLCD.setObjectName(_fromUtf8("usrpVr1UplinkLCD"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(620, 190, 58, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(620, 460, 58, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.usrpVr1DownlinkAvgLCD = QtGui.QLCDNumber(self.tab_2)
        self.usrpVr1DownlinkAvgLCD.setGeometry(QtCore.QRect(680, 220, 64, 23))
        self.usrpVr1DownlinkAvgLCD.setAutoFillBackground(True)
        self.usrpVr1DownlinkAvgLCD.setSmallDecimalPoint(True)
        self.usrpVr1DownlinkAvgLCD.setNumDigits(4)
        self.usrpVr1DownlinkAvgLCD.setDigitCount(4)
        self.usrpVr1DownlinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.usrpVr1DownlinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.usrpVr1DownlinkAvgLCD.setObjectName(_fromUtf8("usrpVr1DownlinkAvgLCD"))
        self.usrpVr1UplinkAvgLCD = QtGui.QLCDNumber(self.tab_2)
        self.usrpVr1UplinkAvgLCD.setGeometry(QtCore.QRect(680, 490, 64, 23))
        self.usrpVr1UplinkAvgLCD.setAutoFillBackground(True)
        self.usrpVr1UplinkAvgLCD.setSmallDecimalPoint(True)
        self.usrpVr1UplinkAvgLCD.setNumDigits(4)
        self.usrpVr1UplinkAvgLCD.setDigitCount(4)
        self.usrpVr1UplinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.usrpVr1UplinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.usrpVr1UplinkAvgLCD.setObjectName(_fromUtf8("usrpVr1UplinkAvgLCD"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(640, 220, 31, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(640, 490, 31, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.usrpVr2DownlinkLCD = QtGui.QLCDNumber(self.tab_2)
        self.usrpVr2DownlinkLCD.setGeometry(QtCore.QRect(750, 190, 64, 23))
        self.usrpVr2DownlinkLCD.setAutoFillBackground(True)
        self.usrpVr2DownlinkLCD.setSmallDecimalPoint(True)
        self.usrpVr2DownlinkLCD.setNumDigits(4)
        self.usrpVr2DownlinkLCD.setDigitCount(4)
        self.usrpVr2DownlinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.usrpVr2DownlinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.usrpVr2DownlinkLCD.setObjectName(_fromUtf8("usrpVr2DownlinkLCD"))
        self.usrpVr2DownlinkAvgLCD = QtGui.QLCDNumber(self.tab_2)
        self.usrpVr2DownlinkAvgLCD.setGeometry(QtCore.QRect(750, 220, 64, 23))
        self.usrpVr2DownlinkAvgLCD.setAutoFillBackground(True)
        self.usrpVr2DownlinkAvgLCD.setSmallDecimalPoint(True)
        self.usrpVr2DownlinkAvgLCD.setNumDigits(4)
        self.usrpVr2DownlinkAvgLCD.setDigitCount(4)
        self.usrpVr2DownlinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.usrpVr2DownlinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.usrpVr2DownlinkAvgLCD.setObjectName(_fromUtf8("usrpVr2DownlinkAvgLCD"))
        self.usrpVr2UplinkLCD = QtGui.QLCDNumber(self.tab_2)
        self.usrpVr2UplinkLCD.setGeometry(QtCore.QRect(750, 460, 64, 23))
        self.usrpVr2UplinkLCD.setAutoFillBackground(True)
        self.usrpVr2UplinkLCD.setSmallDecimalPoint(True)
        self.usrpVr2UplinkLCD.setNumDigits(4)
        self.usrpVr2UplinkLCD.setDigitCount(4)
        self.usrpVr2UplinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.usrpVr2UplinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.usrpVr2UplinkLCD.setObjectName(_fromUtf8("usrpVr2UplinkLCD"))
        self.usrpVr2UplinkAvgLCD = QtGui.QLCDNumber(self.tab_2)
        self.usrpVr2UplinkAvgLCD.setGeometry(QtCore.QRect(750, 490, 64, 23))
        self.usrpVr2UplinkAvgLCD.setAutoFillBackground(True)
        self.usrpVr2UplinkAvgLCD.setSmallDecimalPoint(True)
        self.usrpVr2UplinkAvgLCD.setNumDigits(4)
        self.usrpVr2UplinkAvgLCD.setDigitCount(4)
        self.usrpVr2UplinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.usrpVr2UplinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.usrpVr2UplinkAvgLCD.setObjectName(_fromUtf8("usrpVr2UplinkAvgLCD"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tabWidget_3 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(870, 10, 841, 751))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tabWidget_3Page1 = QtGui.QWidget()
        self.tabWidget_3Page1.setObjectName(_fromUtf8("tabWidget_3Page1"))
        self.ERDownlinkPlot = PlotWidget(self.tabWidget_3Page1)
        self.ERDownlinkPlot.setGeometry(QtCore.QRect(10, 180, 811, 261))
        self.ERDownlinkPlot.setObjectName(_fromUtf8("ERDownlinkPlot"))
        self.ERUplinkPlot = PlotWidget(self.tabWidget_3Page1)
        self.ERUplinkPlot.setGeometry(QtCore.QRect(10, 450, 811, 261))
        self.ERUplinkPlot.setObjectName(_fromUtf8("ERUplinkPlot"))
        self.ERDownlinkLCD = QtGui.QLCDNumber(self.tabWidget_3Page1)
        self.ERDownlinkLCD.setGeometry(QtCore.QRect(750, 200, 64, 23))
        self.ERDownlinkLCD.setAutoFillBackground(True)
        self.ERDownlinkLCD.setSmallDecimalPoint(True)
        self.ERDownlinkLCD.setNumDigits(4)
        self.ERDownlinkLCD.setDigitCount(4)
        self.ERDownlinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.ERDownlinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.ERDownlinkLCD.setObjectName(_fromUtf8("ERDownlinkLCD"))
        self.ERUplinkLCD = QtGui.QLCDNumber(self.tabWidget_3Page1)
        self.ERUplinkLCD.setGeometry(QtCore.QRect(750, 460, 64, 23))
        self.ERUplinkLCD.setAutoFillBackground(True)
        self.ERUplinkLCD.setSmallDecimalPoint(True)
        self.ERUplinkLCD.setNumDigits(4)
        self.ERUplinkLCD.setDigitCount(4)
        self.ERUplinkLCD.setMode(QtGui.QLCDNumber.Dec)
        self.ERUplinkLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.ERUplinkLCD.setObjectName(_fromUtf8("ERUplinkLCD"))
        self.label_10 = QtGui.QLabel(self.tabWidget_3Page1)
        self.label_10.setGeometry(QtCore.QRect(690, 200, 58, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tabWidget_3Page1)
        self.label_11.setGeometry(QtCore.QRect(690, 460, 58, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.ERDownlinkAvgLCD = QtGui.QLCDNumber(self.tabWidget_3Page1)
        self.ERDownlinkAvgLCD.setGeometry(QtCore.QRect(750, 230, 64, 23))
        self.ERDownlinkAvgLCD.setAutoFillBackground(True)
        self.ERDownlinkAvgLCD.setSmallDecimalPoint(True)
        self.ERDownlinkAvgLCD.setNumDigits(4)
        self.ERDownlinkAvgLCD.setDigitCount(4)
        self.ERDownlinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.ERDownlinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.ERDownlinkAvgLCD.setObjectName(_fromUtf8("ERDownlinkAvgLCD"))
        self.label_17 = QtGui.QLabel(self.tabWidget_3Page1)
        self.label_17.setGeometry(QtCore.QRect(710, 230, 31, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.ERUplinkAvgLCD = QtGui.QLCDNumber(self.tabWidget_3Page1)
        self.ERUplinkAvgLCD.setGeometry(QtCore.QRect(750, 490, 64, 23))
        self.ERUplinkAvgLCD.setAutoFillBackground(True)
        self.ERUplinkAvgLCD.setSmallDecimalPoint(True)
        self.ERUplinkAvgLCD.setNumDigits(4)
        self.ERUplinkAvgLCD.setDigitCount(4)
        self.ERUplinkAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.ERUplinkAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.ERUplinkAvgLCD.setObjectName(_fromUtf8("ERUplinkAvgLCD"))
        self.label_18 = QtGui.QLabel(self.tabWidget_3Page1)
        self.label_18.setGeometry(QtCore.QRect(710, 490, 31, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.ERDownlinkLabel = QtGui.QLabel(self.tabWidget_3Page1)
        self.ERDownlinkLabel.setGeometry(QtCore.QRect(170, 30, 341, 16))
        self.ERDownlinkLabel.setObjectName(_fromUtf8("ERDownlinkLabel"))
        self.ERUplinkLabel = QtGui.QLabel(self.tabWidget_3Page1)
        self.ERUplinkLabel.setGeometry(QtCore.QRect(170, 60, 341, 16))
        self.ERUplinkLabel.setObjectName(_fromUtf8("ERUplinkLabel"))
        self.label_25 = QtGui.QLabel(self.tabWidget_3Page1)
        self.label_25.setGeometry(QtCore.QRect(20, 30, 131, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tabWidget_3Page1)
        self.label_26.setGeometry(QtCore.QRect(40, 60, 111, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.tabWidget_3.addTab(self.tabWidget_3Page1, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.regionalCPUPlot = PlotWidget(self.tab_3)
        self.regionalCPUPlot.setGeometry(QtCore.QRect(10, 180, 811, 261))
        self.regionalCPUPlot.setObjectName(_fromUtf8("regionalCPUPlot"))
        self.edgeCPUPlot = PlotWidget(self.tab_3)
        self.edgeCPUPlot.setGeometry(QtCore.QRect(10, 450, 811, 261))
        self.edgeCPUPlot.setObjectName(_fromUtf8("edgeCPUPlot"))
        self.regionalCPULCD = QtGui.QLCDNumber(self.tab_3)
        self.regionalCPULCD.setGeometry(QtCore.QRect(750, 200, 64, 23))
        self.regionalCPULCD.setAutoFillBackground(True)
        self.regionalCPULCD.setSmallDecimalPoint(True)
        self.regionalCPULCD.setNumDigits(4)
        self.regionalCPULCD.setDigitCount(4)
        self.regionalCPULCD.setMode(QtGui.QLCDNumber.Dec)
        self.regionalCPULCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.regionalCPULCD.setObjectName(_fromUtf8("regionalCPULCD"))
        self.edgeCPULCD = QtGui.QLCDNumber(self.tab_3)
        self.edgeCPULCD.setGeometry(QtCore.QRect(750, 460, 64, 23))
        self.edgeCPULCD.setAutoFillBackground(True)
        self.edgeCPULCD.setSmallDecimalPoint(True)
        self.edgeCPULCD.setNumDigits(4)
        self.edgeCPULCD.setDigitCount(4)
        self.edgeCPULCD.setMode(QtGui.QLCDNumber.Dec)
        self.edgeCPULCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.edgeCPULCD.setObjectName(_fromUtf8("edgeCPULCD"))
        self.regionalCPUAvgLCD = QtGui.QLCDNumber(self.tab_3)
        self.regionalCPUAvgLCD.setGeometry(QtCore.QRect(750, 230, 64, 23))
        self.regionalCPUAvgLCD.setAutoFillBackground(True)
        self.regionalCPUAvgLCD.setSmallDecimalPoint(True)
        self.regionalCPUAvgLCD.setNumDigits(4)
        self.regionalCPUAvgLCD.setDigitCount(4)
        self.regionalCPUAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.regionalCPUAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.regionalCPUAvgLCD.setObjectName(_fromUtf8("regionalCPUAvgLCD"))
        self.edgeCPUAvgLCD = QtGui.QLCDNumber(self.tab_3)
        self.edgeCPUAvgLCD.setGeometry(QtCore.QRect(750, 490, 64, 23))
        self.edgeCPUAvgLCD.setAutoFillBackground(True)
        self.edgeCPUAvgLCD.setSmallDecimalPoint(True)
        self.edgeCPUAvgLCD.setNumDigits(4)
        self.edgeCPUAvgLCD.setDigitCount(4)
        self.edgeCPUAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.edgeCPUAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.edgeCPUAvgLCD.setObjectName(_fromUtf8("edgeCPUAvgLCD"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(690, 200, 58, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(710, 230, 31, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(710, 490, 31, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(690, 460, 58, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_33 = QtGui.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(50, 60, 101, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.edgeCPULabel = QtGui.QLabel(self.tab_3)
        self.edgeCPULabel.setGeometry(QtCore.QRect(170, 60, 341, 16))
        self.edgeCPULabel.setObjectName(_fromUtf8("edgeCPULabel"))
        self.regionalCPULabel = QtGui.QLabel(self.tab_3)
        self.regionalCPULabel.setGeometry(QtCore.QRect(170, 30, 341, 16))
        self.regionalCPULabel.setObjectName(_fromUtf8("regionalCPULabel"))
        self.label_34 = QtGui.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(30, 30, 131, 20))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.tabWidget_3.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.regionalRAMPlot = PlotWidget(self.tab_4)
        self.regionalRAMPlot.setGeometry(QtCore.QRect(10, 180, 811, 261))
        self.regionalRAMPlot.setObjectName(_fromUtf8("regionalRAMPlot"))
        self.label_27 = QtGui.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(690, 200, 58, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.regionalRAMAvgLCD = QtGui.QLCDNumber(self.tab_4)
        self.regionalRAMAvgLCD.setGeometry(QtCore.QRect(750, 230, 64, 23))
        self.regionalRAMAvgLCD.setAutoFillBackground(True)
        self.regionalRAMAvgLCD.setSmallDecimalPoint(True)
        self.regionalRAMAvgLCD.setNumDigits(4)
        self.regionalRAMAvgLCD.setDigitCount(4)
        self.regionalRAMAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.regionalRAMAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.regionalRAMAvgLCD.setObjectName(_fromUtf8("regionalRAMAvgLCD"))
        self.regionalRAMLCD = QtGui.QLCDNumber(self.tab_4)
        self.regionalRAMLCD.setGeometry(QtCore.QRect(750, 200, 64, 23))
        self.regionalRAMLCD.setAutoFillBackground(True)
        self.regionalRAMLCD.setSmallDecimalPoint(True)
        self.regionalRAMLCD.setNumDigits(4)
        self.regionalRAMLCD.setDigitCount(4)
        self.regionalRAMLCD.setMode(QtGui.QLCDNumber.Dec)
        self.regionalRAMLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.regionalRAMLCD.setObjectName(_fromUtf8("regionalRAMLCD"))
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(710, 230, 31, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(690, 460, 58, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.edgeRAMAvgLCD = QtGui.QLCDNumber(self.tab_4)
        self.edgeRAMAvgLCD.setGeometry(QtCore.QRect(750, 490, 64, 23))
        self.edgeRAMAvgLCD.setAutoFillBackground(True)
        self.edgeRAMAvgLCD.setSmallDecimalPoint(True)
        self.edgeRAMAvgLCD.setNumDigits(4)
        self.edgeRAMAvgLCD.setDigitCount(4)
        self.edgeRAMAvgLCD.setMode(QtGui.QLCDNumber.Dec)
        self.edgeRAMAvgLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.edgeRAMAvgLCD.setObjectName(_fromUtf8("edgeRAMAvgLCD"))
        self.edgeRAMPlot = PlotWidget(self.tab_4)
        self.edgeRAMPlot.setGeometry(QtCore.QRect(10, 450, 811, 261))
        self.edgeRAMPlot.setObjectName(_fromUtf8("edgeRAMPlot"))
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(710, 490, 31, 21))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.edgeRAMLCD = QtGui.QLCDNumber(self.tab_4)
        self.edgeRAMLCD.setGeometry(QtCore.QRect(750, 460, 64, 23))
        self.edgeRAMLCD.setAutoFillBackground(True)
        self.edgeRAMLCD.setSmallDecimalPoint(True)
        self.edgeRAMLCD.setNumDigits(4)
        self.edgeRAMLCD.setDigitCount(4)
        self.edgeRAMLCD.setMode(QtGui.QLCDNumber.Dec)
        self.edgeRAMLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.edgeRAMLCD.setObjectName(_fromUtf8("edgeRAMLCD"))
        self.regionalRAMLabel = QtGui.QLabel(self.tab_4)
        self.regionalRAMLabel.setGeometry(QtCore.QRect(170, 30, 341, 16))
        self.regionalRAMLabel.setObjectName(_fromUtf8("regionalRAMLabel"))
        self.label_35 = QtGui.QLabel(self.tab_4)
        self.label_35.setGeometry(QtCore.QRect(50, 60, 101, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.edgeRAMLabel = QtGui.QLabel(self.tab_4)
        self.edgeRAMLabel.setGeometry(QtCore.QRect(170, 60, 341, 16))
        self.edgeRAMLabel.setObjectName(_fromUtf8("edgeRAMLabel"))
        self.label_36 = QtGui.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(30, 30, 131, 20))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.edgeRAMPlot.raise_()
        self.regionalRAMPlot.raise_()
        self.label_27.raise_()
        self.regionalRAMAvgLCD.raise_()
        self.regionalRAMLCD.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.edgeRAMAvgLCD.raise_()
        self.label_30.raise_()
        self.edgeRAMLCD.raise_()
        self.regionalRAMLabel.raise_()
        self.label_35.raise_()
        self.edgeRAMLabel.raise_()
        self.label_36.raise_()
        self.tabWidget_3.addTab(self.tab_4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QObject.connect(self.vr1Split2Group, QtCore.SIGNAL(_fromUtf8("buttonPressed(QAbstractButton*)")), MainWindow.migrateVr1Split2)
        QtCore.QObject.connect(self.vr1Split1Group, QtCore.SIGNAL(_fromUtf8("buttonPressed(QAbstractButton*)")), MainWindow.migrateVr1Split1)
        QtCore.QObject.connect(self.vr1Split3Group, QtCore.SIGNAL(_fromUtf8("buttonPressed(QAbstractButton*)")), MainWindow.migrateVr1Split3)
        QtCore.QObject.connect(self.vr2Group, QtCore.SIGNAL(_fromUtf8("buttonPressed(QAbstractButton*)")), MainWindow.migrateVr2Split)
        QtCore.QObject.connect(self.vr1Amplitude, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.vr1Amplitude)
        QtCore.QObject.connect(self.vr2Amplitude, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.vr2Amplitude)
        QtCore.QObject.connect(self.vr1ToogleAll, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.vr1Toogled)
        QtCore.QObject.connect(self.vr2ToogleAll, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.vr2Toogled)
        QtCore.QObject.connect(self.vr1AllEdge_2, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.vr1MigrateAllRegional)
        QtCore.QObject.connect(self.vr1AllEdge, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.vr1MigrateAllEdge)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.vr1Split1RadioEdge.setText(_translate("MainWindow", "Edge", None))
        self.vr1Split1RadioRegional.setText(_translate("MainWindow", "Regional", None))
        self.label.setText(_translate("MainWindow", "Split 1:", None))
        self.label_2.setText(_translate("MainWindow", "Split 2:", None))
        self.vr1Split2RadioEdge.setText(_translate("MainWindow", "Edge", None))
        self.vr1Split2RadioRegional.setText(_translate("MainWindow", "Regional", None))
        self.label_3.setText(_translate("MainWindow", "Split 3:", None))
        self.vr1Split3RadioEdge.setText(_translate("MainWindow", "Edge", None))
        self.vr1Split3RadioRegional.setText(_translate("MainWindow", "Regional", None))
        self.groupBox.setTitle(_translate("MainWindow", "Split location", None))
        self.vr1ToogleAll.setText(_translate("MainWindow", "Stop All", None))
        self.vr1AllEdge.setText(_translate("MainWindow", "All Edge", None))
        self.vr1AllEdge_2.setText(_translate("MainWindow", "All Regional", None))
        self.label_5.setText(_translate("MainWindow", "Current:", None))
        self.label_12.setText(_translate("MainWindow", "Current:", None))
        self.label_21.setText(_translate("MainWindow", "Avg:", None))
        self.label_22.setText(_translate("MainWindow", "Avg:", None))
        self.label_31.setText(_translate("MainWindow", "Amplitude", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "LTE", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Split location", None))
        self.label_4.setText(_translate("MainWindow", "Split 1:", None))
        self.radioButton_8.setText(_translate("MainWindow", "Regional", None))
        self.radioButton_7.setText(_translate("MainWindow", "Edge", None))
        self.label_13.setText(_translate("MainWindow", "Current:", None))
        self.label_14.setText(_translate("MainWindow", "Current:", None))
        self.label_19.setText(_translate("MainWindow", "Avg:", None))
        self.label_20.setText(_translate("MainWindow", "Avg:", None))
        self.label_32.setText(_translate("MainWindow", "Amplitude", None))
        self.vr2ToogleAll.setText(_translate("MainWindow", "Stop All", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "NB-IoT", None))
        self.label_15.setText(_translate("MainWindow", "Current:", None))
        self.label_16.setText(_translate("MainWindow", "Current:", None))
        self.label_23.setText(_translate("MainWindow", "Avg:", None))
        self.label_24.setText(_translate("MainWindow", "Avg:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "USRP", None))
        self.label_10.setText(_translate("MainWindow", "Current:", None))
        self.label_11.setText(_translate("MainWindow", "Current:", None))
        self.label_17.setText(_translate("MainWindow", "Avg:", None))
        self.label_18.setText(_translate("MainWindow", "Avg:", None))
        self.ERDownlinkLabel.setText(_translate("MainWindow", "X", None))
        self.ERUplinkLabel.setText(_translate("MainWindow", "X", None))
        self.label_25.setText(_translate("MainWindow", "Downlink traffic from:", None))
        self.label_26.setText(_translate("MainWindow", "Uplink traffic from: ", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tabWidget_3Page1), _translate("MainWindow", "Edge-Regional Network", None))
        self.label_6.setText(_translate("MainWindow", "Current:", None))
        self.label_7.setText(_translate("MainWindow", "Avg:", None))
        self.label_8.setText(_translate("MainWindow", "Avg:", None))
        self.label_9.setText(_translate("MainWindow", "Current:", None))
        self.label_33.setText(_translate("MainWindow", "Edge CPU usage:", None))
        self.edgeCPULabel.setText(_translate("MainWindow", "X", None))
        self.regionalCPULabel.setText(_translate("MainWindow", "X", None))
        self.label_34.setText(_translate("MainWindow", "Regional CPU usage:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("MainWindow", "Edge-Regional CPU", None))
        self.label_27.setText(_translate("MainWindow", "Current:", None))
        self.label_28.setText(_translate("MainWindow", "Avg:", None))
        self.label_29.setText(_translate("MainWindow", "Current:", None))
        self.label_30.setText(_translate("MainWindow", "Avg:", None))
        self.regionalRAMLabel.setText(_translate("MainWindow", "X", None))
        self.label_35.setText(_translate("MainWindow", "Edge RAM usage:", None))
        self.edgeRAMLabel.setText(_translate("MainWindow", "X", None))
        self.label_36.setText(_translate("MainWindow", "Regional RAM usage:", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("MainWindow", "Edge-Regional RAM", None))

from pyqtgraph import PlotWidget
import resources_rc
